FROM node:18-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --only=production

COPY src/config ./src/config
COPY src/models ./src/models
COPY src/middleware ./src/middleware
COPY src/services/order ./src/services/order

EXPOSE 3003

CMD ["node", "src/services/order/server.js"]
